# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

permissions: read-all
name: Build / test
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake_ubuntu_2604:
    name: Build and test ${{ matrix.name }}
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Clang-20
            extra_deps: clang-20
            c_compiler: clang-20
            cxx_compiler: clang++-20
            extra_cmake_flags: -DHWY_ENABLE_CONTRIB=OFF
            cxx_standard: 17

          - name: Clang-21 (VQSort disabled)
            extra_deps: clang-21
            c_compiler: clang-21
            cxx_compiler: clang++-21
            cxx_flags: -DHWY_DISABLE_VQSORT=1
            cxx_standard: 17

          - name: Clang-22
            extra_deps: clang-22
            c_compiler: clang-22
            cxx_compiler: clang++-22
            cxx_standard: 17

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit  # cannot be block - runner does git checkout

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install ${{ matrix.extra_deps }}

      - name: Build and test
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=2
          export CTEST_PARALLEL_LEVEL=2
          CXXFLAGS="${{ matrix.cxx_flags }}" CC=${{ matrix.c_compiler }} CXX=${{ matrix.cxx_compiler }} cmake -DHWY_WARNINGS_ARE_ERRORS=ON -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} ${{ matrix.extra_cmake_flags }} -B out .
          cmake --build out
          ctest --test-dir out
