name: Foreign architectures

on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  aarch64_cmake:
    name: Build and test ${{ matrix.name }} on AArch64
    runs-on: ubuntu-26.04-arm
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: GCC-16
            extra_deps: g++-16
            c_compiler: gcc-16
            cxx_compiler: g++-16
            cxx_flags: -ftrapv
            cxx_standard: 17

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit  # cannot be block - runner does git checkout

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install ${{ matrix.extra_deps }}

      - name: Build
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=2
          export CTEST_PARALLEL_LEVEL=2
          CXXFLAGS="${{ matrix.cxx_flags }}" CC=${{ matrix.c_compiler }} CXX=${{ matrix.cxx_compiler }} cmake -DHWY_WARNINGS_ARE_ERRORS=ON -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} ${{ matrix.extra_cmake_flags }} -B out .
          cmake --build out
      - name: Test
        continue-on-error: true
        run: ctest --test-dir out
