# https://github.com/marketplace/actions/run-on-architecture
name: Foreign architectures

on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  multiarch:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: armv7
            distro: ubuntu_latest
            cxx_flags: -Wno-psabi
            cmake_flags: -DHWY_CMAKE_ARM7:BOOL=ON
          - arch: ppc64le
            distro: ubuntu_latest
          - arch: riscv64
            distro: ubuntu_latest
          - arch: s390x
            distro: ubuntu_latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Build and test
      uses: uraimo/run-on-arch-action@f9b26e3a1a408d5fd530d20c17b9f3f4428ff8d9 # v3.1.0
      id: build
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
        # Not required, but speeds up builds
        githubToken: ${{ github.token }}
        install: |
          apt-get update -q -y
          apt-get install -q -y --no-install-recommends \
                build-essential \
                cmake \
                libgtest-dev \
                ninja-build \
                ;
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=2
          export CTEST_PARALLEL_LEVEL=2
          CXXFLAGS=${{ matrix.cxx_flags }} cmake -GNinja ${{ matrix.cmake_flags }} -DHWY_SYSTEM_GTEST=ON -DHWY_WARNINGS_ARE_ERRORS=ON -B out .
          cmake --build out
          ctest --test-dir out
